# Generated by Django 3.1.4 on 2021-03-17 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='growth250',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grwth_250_rnk', models.IntegerField()),
                ('symbol', models.CharField(max_length=10)),
                ('co_name', models.CharField(max_length=50)),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_change_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_change_pct', models.DecimalField(decimal_places=1, max_digits=5)),
                ('pct_off_high', models.DecimalField(decimal_places=2, max_digits=6)),
                ('pct_vol_chg_vs_50', models.DecimalField(decimal_places=2, max_digits=6)),
                ('vol_avg_50_day_shares', models.BigIntegerField()),
                ('vol_avg_50_day_usd', models.BigIntegerField()),
                ('market_cap_mil', models.DecimalField(decimal_places=1, max_digits=18)),
                ('comp_rating', models.IntegerField()),
                ('eps_rating', models.IntegerField()),
                ('rs_rating', models.IntegerField()),
                ('ad_rating', models.CharField(max_length=10)),
                ('smr_rating', models.CharField(max_length=10)),
                ('ind_grp_rank', models.IntegerField()),
                ('ind_name', models.CharField(max_length=50)),
                ('ipo_date', models.DateField()),
                ('dwnld_dt', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='IndustryGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('no_of_stocks', models.IntegerField()),
                ('ind_grp_rnk', models.IntegerField()),
                ('ind_grp_rnk_last_wk', models.IntegerField()),
                ('ind_grp_rnk_3_mo', models.IntegerField()),
                ('ind_grp_rnk_6_mo', models.IntegerField()),
                ('pct_chg_ytd', models.DecimalField(decimal_places=2, max_digits=6)),
                ('ind_mkt_bal_bil', models.IntegerField()),
                ('dwnld_dt', models.DateField()),
            ],
        ),
    ]
